import { Database as BunDatabase } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import * as schema from "#/db/schema";
import path from "node:path";
import { existsSync, readdirSync } from "node:fs";

const MIGRATION_RETRY_ATTEMPTS = 5;
const MIGRATION_RETRY_DELAY_MS = 100;
const RETRYABLE_MIGRATION_ERROR =
  /SQLITE_BUSY|database is locked|table .* already exists|index .* already exists|duplicate column name/i;

type MigrationRunner = (db: Database, config: { migrationsFolder: string }) => unknown;

export type Database = ReturnType<typeof createDb>;

// ── Database factory ──────────────────────────────────────────────────────────

function createDb(client: BunDatabase) {
  return drizzle({ client, relations: schema.relations });
}

function isDrizzleMigrationsFolder(candidate: string): boolean {
  if (!existsSync(candidate)) {
    return false;
  }

  try {
    return readdirSync(candidate, { withFileTypes: true }).some(
      (entry) => entry.isDirectory() && existsSync(path.join(candidate, entry.name, "migration.sql")),
    );
  } catch {
    return false;
  }
}

function isRetryableMigrationError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return RETRYABLE_MIGRATION_ERROR.test(message);
}

function sleepSync(ms: number): void {
  if (ms <= 0) {
    return;
  }

  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

export function resolveMigrationsFolder(baseDir = __dirname): string {
  // Support source execution plus packaged layouts where migrations may live
  // either in `dist/migrations/*` or directly under `dist/*`.
  const candidates = [
    path.resolve(baseDir, "db", "migrations"),
    path.resolve(baseDir, "..", "src", "db", "migrations"),
    path.resolve(baseDir, "migrations"),
    path.resolve(baseDir),
  ];

  const found = candidates.find(isDrizzleMigrationsFolder);
  if (!found) {
    throw new Error(`Could not find Drizzle migrations folder from '${baseDir}'`);
  }

  return found;
}

export function applyMigrations(
  db: Database,
  options: {
    baseDir?: string;
    migrateFn?: MigrationRunner;
    maxAttempts?: number;
    retryDelayMs?: number;
  } = {},
): void {
  const migrationsFolder = resolveMigrationsFolder(options.baseDir);
  const migrateFn = options.migrateFn ?? migrate;
  const maxAttempts = options.maxAttempts ?? MIGRATION_RETRY_ATTEMPTS;
  const retryDelayMs = options.retryDelayMs ?? MIGRATION_RETRY_DELAY_MS;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      migrateFn(db, { migrationsFolder });
      return;
    } catch (error) {
      if (!isRetryableMigrationError(error) || attempt === maxAttempts) {
        throw error;
      }

      sleepSync(retryDelayMs);
    }
  }
}

/**
 * Open (or create) the depot database at the given path.
 * Runs pending migrations automatically.
 * Use `":memory:"` for tests.
 */
export function openDatabase(path: string): { db: Database; client: BunDatabase } {
  const client = new BunDatabase(path);
  client.run("PRAGMA journal_mode = WAL;");
  client.run("PRAGMA busy_timeout = 5000;");
  client.run("PRAGMA foreign_keys = ON;");
  const db = createDb(client);
  // Apply unapplied SQL migrations generated by drizzle-kit.
  applyMigrations(db);
  return { db, client };
}

/**
 * Resolve the default database path: `~/.depot/depot.db`.
 */
export function defaultDbPath(): string {
  const home = process.env.HOME ?? process.env.USERPROFILE ?? "";
  return `${home.replace(/\\/g, "/")}/.depot/depot.db`;
}
