import type { DotLoaderPreset, DotLoaderProps } from "./types";

export const PRESETS: Record<DotLoaderPreset, Partial<DotLoaderProps>> = {
  thinking: {
    rows: 5,
    cols: 5,
    pattern: "wave-diagonal",
    color: "var(--color-chart-1)",
    speed: 2,
    shape: "circle",
  },
  searching: {
    rows: 4,
    cols: 4,
    pattern: "spinner",
    color: "var(--color-chart-1)",
    speed: 20,
    shape: "circle",
  },
  analysing: {
    rows: 5,
    cols: 5,
    pattern: "random",
    color: "var(--color-chart-4)",
    speed: 8,
    shape: "circle",
  },
  reading: {
    rows: 4,
    cols: 5,
    pattern: "scan-h",
    color: "var(--color-chart-2)",
    speed: 12,
    shape: "rounded",
  },
  debugging: {
    rows: 5,
    cols: 5,
    pattern: "pulse",
    color: "var(--color-destructive)",
    speed: 10,
    shape: "circle",
  },
  generating: {
    rows: 4,
    cols: 5,
    pattern: "fill",
    color: "var(--color-chart-3)",
    speed: 22,
    shape: "rounded",
  },
  "soft-spin": {
    rows: 3,
    cols: 3,
    pattern: "spinner",
    color: "var(--color-muted-foreground)",
    speed: 14,
    shape: "circle",
  },
  "subtle-scan": {
    rows: 2,
    cols: 7,
    pattern: "scan-h",
    color: "var(--color-muted-foreground)",
    speed: 8,
    shape: "rounded",
  },
  terminal: { rows: 5, cols: 5, pattern: "fill", color: "#22c55e", speed: 6, shape: "square" },
};
