/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProjectsIndexRouteImport } from "./routes/projects.index";
import { Route as PrdsIdRouteImport } from "./routes/prds.$id";
import { Route as PrdsIdIndexRouteImport } from "./routes/prds.$id.index";
import { Route as ProjectsIdSettingsRouteImport } from "./routes/projects.$id.settings";
import { Route as ProjectsIdDocsRouteImport } from "./routes/projects.$id.docs";
import { Route as ProjectsIdAdrsIndexRouteImport } from "./routes/projects.$id.adrs.index";
import { Route as ProjectsIdAdrsAdrIdRouteImport } from "./routes/projects.$id.adrs.$adrId";
import { Route as PrdsIdReviewsReviewIdRouteImport } from "./routes/prds.$id.reviews.$reviewId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any);
const PrdsIdRoute = PrdsIdRouteImport.update({
  id: "/prds/$id",
  path: "/prds/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const PrdsIdIndexRoute = PrdsIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrdsIdRoute,
} as any);
const ProjectsIdSettingsRoute = ProjectsIdSettingsRouteImport.update({
  id: "/projects/$id/settings",
  path: "/projects/$id/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIdDocsRoute = ProjectsIdDocsRouteImport.update({
  id: "/projects/$id/docs",
  path: "/projects/$id/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIdAdrsIndexRoute = ProjectsIdAdrsIndexRouteImport.update({
  id: "/projects/$id/adrs/",
  path: "/projects/$id/adrs/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIdAdrsAdrIdRoute = ProjectsIdAdrsAdrIdRouteImport.update({
  id: "/projects/$id/adrs/$adrId",
  path: "/projects/$id/adrs/$adrId",
  getParentRoute: () => rootRouteImport,
} as any);
const PrdsIdReviewsReviewIdRoute = PrdsIdReviewsReviewIdRouteImport.update({
  id: "/reviews/$reviewId",
  path: "/reviews/$reviewId",
  getParentRoute: () => PrdsIdRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/prds/$id": typeof PrdsIdRouteWithChildren;
  "/projects/": typeof ProjectsIndexRoute;
  "/projects/$id/docs": typeof ProjectsIdDocsRoute;
  "/projects/$id/settings": typeof ProjectsIdSettingsRoute;
  "/prds/$id/": typeof PrdsIdIndexRoute;
  "/prds/$id/reviews/$reviewId": typeof PrdsIdReviewsReviewIdRoute;
  "/projects/$id/adrs/$adrId": typeof ProjectsIdAdrsAdrIdRoute;
  "/projects/$id/adrs/": typeof ProjectsIdAdrsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/projects": typeof ProjectsIndexRoute;
  "/projects/$id/docs": typeof ProjectsIdDocsRoute;
  "/projects/$id/settings": typeof ProjectsIdSettingsRoute;
  "/prds/$id": typeof PrdsIdIndexRoute;
  "/prds/$id/reviews/$reviewId": typeof PrdsIdReviewsReviewIdRoute;
  "/projects/$id/adrs/$adrId": typeof ProjectsIdAdrsAdrIdRoute;
  "/projects/$id/adrs": typeof ProjectsIdAdrsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/prds/$id": typeof PrdsIdRouteWithChildren;
  "/projects/": typeof ProjectsIndexRoute;
  "/projects/$id/docs": typeof ProjectsIdDocsRoute;
  "/projects/$id/settings": typeof ProjectsIdSettingsRoute;
  "/prds/$id/": typeof PrdsIdIndexRoute;
  "/prds/$id/reviews/$reviewId": typeof PrdsIdReviewsReviewIdRoute;
  "/projects/$id/adrs/$adrId": typeof ProjectsIdAdrsAdrIdRoute;
  "/projects/$id/adrs/": typeof ProjectsIdAdrsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/prds/$id"
    | "/projects/"
    | "/projects/$id/docs"
    | "/projects/$id/settings"
    | "/prds/$id/"
    | "/prds/$id/reviews/$reviewId"
    | "/projects/$id/adrs/$adrId"
    | "/projects/$id/adrs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/projects"
    | "/projects/$id/docs"
    | "/projects/$id/settings"
    | "/prds/$id"
    | "/prds/$id/reviews/$reviewId"
    | "/projects/$id/adrs/$adrId"
    | "/projects/$id/adrs";
  id:
    | "__root__"
    | "/"
    | "/prds/$id"
    | "/projects/"
    | "/projects/$id/docs"
    | "/projects/$id/settings"
    | "/prds/$id/"
    | "/prds/$id/reviews/$reviewId"
    | "/projects/$id/adrs/$adrId"
    | "/projects/$id/adrs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PrdsIdRoute: typeof PrdsIdRouteWithChildren;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
  ProjectsIdDocsRoute: typeof ProjectsIdDocsRoute;
  ProjectsIdSettingsRoute: typeof ProjectsIdSettingsRoute;
  ProjectsIdAdrsAdrIdRoute: typeof ProjectsIdAdrsAdrIdRoute;
  ProjectsIdAdrsIndexRoute: typeof ProjectsIdAdrsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/": {
      id: "/projects/";
      path: "/projects";
      fullPath: "/projects/";
      preLoaderRoute: typeof ProjectsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/prds/$id": {
      id: "/prds/$id";
      path: "/prds/$id";
      fullPath: "/prds/$id";
      preLoaderRoute: typeof PrdsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/prds/$id/": {
      id: "/prds/$id/";
      path: "/";
      fullPath: "/prds/$id/";
      preLoaderRoute: typeof PrdsIdIndexRouteImport;
      parentRoute: typeof PrdsIdRoute;
    };
    "/projects/$id/settings": {
      id: "/projects/$id/settings";
      path: "/projects/$id/settings";
      fullPath: "/projects/$id/settings";
      preLoaderRoute: typeof ProjectsIdSettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$id/docs": {
      id: "/projects/$id/docs";
      path: "/projects/$id/docs";
      fullPath: "/projects/$id/docs";
      preLoaderRoute: typeof ProjectsIdDocsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$id/adrs/": {
      id: "/projects/$id/adrs/";
      path: "/projects/$id/adrs";
      fullPath: "/projects/$id/adrs/";
      preLoaderRoute: typeof ProjectsIdAdrsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$id/adrs/$adrId": {
      id: "/projects/$id/adrs/$adrId";
      path: "/projects/$id/adrs/$adrId";
      fullPath: "/projects/$id/adrs/$adrId";
      preLoaderRoute: typeof ProjectsIdAdrsAdrIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/prds/$id/reviews/$reviewId": {
      id: "/prds/$id/reviews/$reviewId";
      path: "/reviews/$reviewId";
      fullPath: "/prds/$id/reviews/$reviewId";
      preLoaderRoute: typeof PrdsIdReviewsReviewIdRouteImport;
      parentRoute: typeof PrdsIdRoute;
    };
  }
}

interface PrdsIdRouteChildren {
  PrdsIdIndexRoute: typeof PrdsIdIndexRoute;
  PrdsIdReviewsReviewIdRoute: typeof PrdsIdReviewsReviewIdRoute;
}

const PrdsIdRouteChildren: PrdsIdRouteChildren = {
  PrdsIdIndexRoute: PrdsIdIndexRoute,
  PrdsIdReviewsReviewIdRoute: PrdsIdReviewsReviewIdRoute,
};

const PrdsIdRouteWithChildren =
  PrdsIdRoute._addFileChildren(PrdsIdRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrdsIdRoute: PrdsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdDocsRoute: ProjectsIdDocsRoute,
  ProjectsIdSettingsRoute: ProjectsIdSettingsRoute,
  ProjectsIdAdrsAdrIdRoute: ProjectsIdAdrsAdrIdRoute,
  ProjectsIdAdrsIndexRoute: ProjectsIdAdrsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
